---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Go Fuzzing Tests

on:
  workflow_dispatch:
    inputs:
      run_catalog:
        description: 'Run Catalog fuzzing tests'
        required: false
        type: boolean
        default: true
      fuzz_seconds_catalog:
        description: 'Duration per test case in secs. Total duration is secs x # of test cases'
        required: false
        type: number
        default: 60
  # Scheduled workflows will only run on the default branch. Input values from workflow_dispatch will be null when schedule event is triggered
  schedule:
    - cron: "0 0 * * 6"   # every week, at 00:00 on Saturday

permissions:
  contents: read

jobs:
  go-fuzz-catalog:
    if: ${{ inputs.run_catalog || github.event_name == 'schedule' }}
    name: Catalog Go Fuzzing Tests
    uses: open-edge-platform/orch-ci/.github/workflows/apporch-go-fuzz.yml@65fc743e0c69b8529188b89dede3acfe2897b2e0  # 0.1.33
    with:
      # Declare 4800 secs duration since schedule event will not pick up input values from workflow_dispatch
      fuzz_seconds: ${{ fromJSON(inputs.fuzz_seconds_catalog) || 4800 }}
      test_data_dir: ./internal/northbound/testdata/fuzz
